### ISSUE TITLE
🚨 bug issue 생성 테스트

### ISSUE THREAD

**Issue by eeeyooon** [eeeyooon/git-automation#7]
## 🌳 작업 브랜치

`bug/7`

## 🚨 BUG 개요

Bug Issue 생성 테스트

## ✅ TODO 및 진행현황

- [x] 브랜치 이름 잘 가져오는지 [branchType/issueNumber]
- [x] assignee 자동 할당
- [x] label 자동 할당
